-- Run only with the database-owning role.
-- This file records the original development-access grants.


USE ROLE GRIZZLY03_CREATE_DB_RL;


GRANT USAGE
    ON DATABASE CHAINPROOF
    TO ROLE GRIZZLY03_LEARNER_RL;


GRANT ALL PRIVILEGES
    ON SCHEMA CHAINPROOF.RAW
    TO ROLE GRIZZLY03_LEARNER_RL;


GRANT ALL PRIVILEGES
    ON SCHEMA CHAINPROOF.CORE
    TO ROLE GRIZZLY03_LEARNER_RL;


GRANT ALL PRIVILEGES
    ON SCHEMA CHAINPROOF.GOVERNANCE
    TO ROLE GRIZZLY03_LEARNER_RL;


GRANT ALL PRIVILEGES
    ON SCHEMA CHAINPROOF.SEMANTIC
    TO ROLE GRIZZLY03_LEARNER_RL;


GRANT ALL PRIVILEGES
    ON SCHEMA CHAINPROOF.APP
    TO ROLE GRIZZLY03_LEARNER_RL;


GRANT ALL PRIVILEGES
    ON SCHEMA CHAINPROOF.AUDIT
    TO ROLE GRIZZLY03_LEARNER_RL;
