

-- Run only with the database-owning role.

USE ROLE GRIZZLY03_CREATE_DB_RL;

GRANT USAGE
ON DATABASE CHAINPROOF
TO ROLE GRIZZLY03_LEARNER_RL;

GRANT ALL PRIVILEGES
ON SCHEMA CHAINPROOF_RAW
TO ROLE GRIZZLY03_LEARNER_RL;

GRANT ALL PRIVILEGES
ON SCHEMA CHAINPROOF_CORE
TO ROLE GRIZZLY03_LEARNER_RL;

GRANT ALL PRIVILEGES
ON SCHEMA CHAINPROOF_GOVERNANCE
TO ROLE GRIZZLY03_LEARNER_RL;

GRANT ALL PRIVILEGES
ON SCHEMA CHAINPROOF_SEMANTIC
TO ROLE GRIZZLY03_LEARNER_RL;

GRANT ALL PRIVILEGES
ON SCHEMA CHAINPROOF_APP
TO ROLE GRIZZLY03_LEARNER_RL;

GRANT ALL PRIVILEGES
ON SCHEMA CHAINPROOF_AUDIT
TO ROLE GRIZZLY03_LEARNER_RL;
