-- One-time reset for unapproved Part 4 draft tables.
-- This file is executed only when PART4_RESET_DRAFT_TABLES=1.

USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.RAW;

DROP TABLE IF EXISTS SRC_QUALITY_INSPECTIONS;
DROP TABLE IF EXISTS SRC_LOGISTICS_RECEIPTS;
DROP TABLE IF EXISTS SRC_LOGISTICS_SHIPMENT_LINES;
DROP TABLE IF EXISTS SRC_LOGISTICS_SHIPMENTS;
DROP TABLE IF EXISTS SRC_ERP_PURCHASE_ORDER_LINES;
DROP TABLE IF EXISTS SRC_ERP_PURCHASE_ORDERS;
DROP TABLE IF EXISTS SRC_PLANNING_REQUIREMENTS;
DROP TABLE IF EXISTS SRC_IDENTITY_PERSONA_MAP;
DROP TABLE IF EXISTS SRC_LOGISTICS_CARRIER_MASTER;
DROP TABLE IF EXISTS SRC_ERP_PLANT_MASTER;
DROP TABLE IF EXISTS SRC_ERP_PART_MASTER;
DROP TABLE IF EXISTS SRC_SUPPLIER_MASTER;
