-- Part 4: Load CSV data from stage into RAW tables
-- TRUNCATE + COPY pattern ensures idempotency.

USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.RAW;

TRUNCATE TABLE SRC_SUPPLIER_MASTER;
COPY INTO SRC_SUPPLIER_MASTER FROM @PART4_STAGE/supplier_master.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_ERP_PART_MASTER;
COPY INTO SRC_ERP_PART_MASTER FROM @PART4_STAGE/erp_part_master.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_ERP_PLANT_MASTER;
COPY INTO SRC_ERP_PLANT_MASTER FROM @PART4_STAGE/erp_plant_master.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_LOGISTICS_CARRIER_MASTER;
COPY INTO SRC_LOGISTICS_CARRIER_MASTER FROM @PART4_STAGE/logistics_carrier_master.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_ERP_PURCHASE_ORDERS;
COPY INTO SRC_ERP_PURCHASE_ORDERS FROM @PART4_STAGE/erp_purchase_orders.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_ERP_PURCHASE_ORDER_LINES;
COPY INTO SRC_ERP_PURCHASE_ORDER_LINES FROM @PART4_STAGE/erp_purchase_order_lines.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_LOGISTICS_SHIPMENTS;
COPY INTO SRC_LOGISTICS_SHIPMENTS FROM @PART4_STAGE/logistics_shipments.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_LOGISTICS_SHIPMENT_LINES;
COPY INTO SRC_LOGISTICS_SHIPMENT_LINES FROM @PART4_STAGE/logistics_shipment_lines.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_LOGISTICS_RECEIPTS;
COPY INTO SRC_LOGISTICS_RECEIPTS FROM @PART4_STAGE/logistics_receipts.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_QUALITY_INSPECTIONS;
COPY INTO SRC_QUALITY_INSPECTIONS FROM @PART4_STAGE/quality_inspections.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_PLANNING_REQUIREMENTS;
COPY INTO SRC_PLANNING_REQUIREMENTS FROM @PART4_STAGE/planning_requirements.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;

TRUNCATE TABLE SRC_IDENTITY_PERSONA_MAP;
COPY INTO SRC_IDENTITY_PERSONA_MAP FROM @PART4_STAGE/identity_persona_map.csv
    FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE)
    ON_ERROR = CONTINUE;
