-- Part 4: Load CSV data from stage into RAW tables
-- Uses METADATA$ virtual columns for ingestion traceability.
-- ON_ERROR = ABORT_STATEMENT stops on any row error.

USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.RAW;

COPY INTO SRC_SUPPLIER_MASTER
FROM (
    SELECT $1, $2, $3, $4, $5, $6,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/supplier_master.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_ERP_PART_MASTER
FROM (
    SELECT $1, $2, $3, $4, $5, $6,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/erp_part_master.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_ERP_PLANT_MASTER
FROM (
    SELECT $1, $2, $3, $4, $5, $6,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/erp_plant_master.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_LOGISTICS_CARRIER_MASTER
FROM (
    SELECT $1, $2, $3, $4,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/logistics_carrier_master.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_ERP_PURCHASE_ORDERS
FROM (
    SELECT $1, $2, $3, $4, $5,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/erp_purchase_orders.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_ERP_PURCHASE_ORDER_LINES
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/erp_purchase_order_lines.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_LOGISTICS_SHIPMENTS
FROM (
    SELECT $1, $2, $3, $4, $5,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/logistics_shipments.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_LOGISTICS_SHIPMENT_LINES
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/logistics_shipment_lines.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_LOGISTICS_RECEIPTS
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/logistics_receipts.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_QUALITY_INSPECTIONS
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/quality_inspections.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_PLANNING_REQUIREMENTS
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/planning_requirements.csv
)
ON_ERROR = ABORT_STATEMENT;

COPY INTO SRC_IDENTITY_PERSONA_MAP
FROM (
    SELECT $1, $2, $3, $4, $5,
        'part4_v1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, CURRENT_TIMESTAMP()
    FROM @PART4_SOURCE_STAGE/v1/identity_persona_map.csv
)
ON_ERROR = ABORT_STATEMENT;
