-- Part 4: Truncate and load CSV data from stage into RAW tables.
-- Uses METADATA$ virtual columns for ingestion traceability.
-- FORCE = TRUE ensures reload even if files were previously loaded.
-- ON_ERROR = ABORT_STATEMENT stops on any row error.
-- Batch ID: PART4_SYNTHETIC_V1
-- loaded_at populated from METADATA$START_SCAN_TIME.

USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.RAW;

TRUNCATE TABLE SRC_SUPPLIER_MASTER;
COPY INTO SRC_SUPPLIER_MASTER
FROM (
    SELECT $1, $2, $3, $4, $5, $6,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/supplier_master.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_ERP_PART_MASTER;
COPY INTO SRC_ERP_PART_MASTER
FROM (
    SELECT $1, $2, $3, $4, $5, $6,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/erp_part_master.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_ERP_PLANT_MASTER;
COPY INTO SRC_ERP_PLANT_MASTER
FROM (
    SELECT $1, $2, $3, $4, $5, $6,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/erp_plant_master.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_LOGISTICS_CARRIER_MASTER;
COPY INTO SRC_LOGISTICS_CARRIER_MASTER
FROM (
    SELECT $1, $2, $3, $4,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/logistics_carrier_master.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_ERP_PURCHASE_ORDERS;
COPY INTO SRC_ERP_PURCHASE_ORDERS
FROM (
    SELECT $1, $2, $3, $4, $5,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/erp_purchase_orders.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_ERP_PURCHASE_ORDER_LINES;
COPY INTO SRC_ERP_PURCHASE_ORDER_LINES
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/erp_purchase_order_lines.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_LOGISTICS_SHIPMENTS;
COPY INTO SRC_LOGISTICS_SHIPMENTS
FROM (
    SELECT $1, $2, $3, $4, $5,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/logistics_shipments.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_LOGISTICS_SHIPMENT_LINES;
COPY INTO SRC_LOGISTICS_SHIPMENT_LINES
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/logistics_shipment_lines.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_LOGISTICS_RECEIPTS;
COPY INTO SRC_LOGISTICS_RECEIPTS
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/logistics_receipts.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_QUALITY_INSPECTIONS;
COPY INTO SRC_QUALITY_INSPECTIONS
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/quality_inspections.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_PLANNING_REQUIREMENTS;
COPY INTO SRC_PLANNING_REQUIREMENTS
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/planning_requirements.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;

TRUNCATE TABLE SRC_IDENTITY_PERSONA_MAP;
COPY INTO SRC_IDENTITY_PERSONA_MAP
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8,
        'PART4_SYNTHETIC_V1', METADATA$FILENAME, METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME
    FROM @PART4_SOURCE_STAGE/v1/identity_persona_map.csv
)
FORCE = TRUE
ON_ERROR = ABORT_STATEMENT;
