-- Part 4: RAW data validation — readable PASS/FAIL results.

USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.RAW;

-- Stage files
SELECT 'stage_files' AS check_name, COUNT(*) AS actual, 12 AS expected,
    CASE WHEN COUNT(*) = 12 THEN 'PASS' ELSE 'FAIL' END AS status
FROM DIRECTORY(@PART4_SOURCE_STAGE);

-- File format exists
SELECT 'file_format_exists' AS check_name,
    CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS status
FROM INFORMATION_SCHEMA.FILE_FORMATS
WHERE FILE_FORMAT_NAME = 'PART4_CSV_FORMAT';

-- Per-table row counts
SELECT table_name, row_count AS actual,
    CASE table_name
        WHEN 'SRC_SUPPLIER_MASTER' THEN 4
        WHEN 'SRC_ERP_PART_MASTER' THEN 1
        WHEN 'SRC_ERP_PLANT_MASTER' THEN 1
        WHEN 'SRC_LOGISTICS_CARRIER_MASTER' THEN 3
        WHEN 'SRC_ERP_PURCHASE_ORDERS' THEN 13
        WHEN 'SRC_ERP_PURCHASE_ORDER_LINES' THEN 13
        WHEN 'SRC_LOGISTICS_SHIPMENTS' THEN 15
        WHEN 'SRC_LOGISTICS_SHIPMENT_LINES' THEN 15
        WHEN 'SRC_LOGISTICS_RECEIPTS' THEN 14
        WHEN 'SRC_QUALITY_INSPECTIONS' THEN 13
        WHEN 'SRC_PLANNING_REQUIREMENTS' THEN 13
        WHEN 'SRC_IDENTITY_PERSONA_MAP' THEN 5
    END AS expected,
    CASE WHEN row_count = CASE table_name
        WHEN 'SRC_SUPPLIER_MASTER' THEN 4
        WHEN 'SRC_ERP_PART_MASTER' THEN 1
        WHEN 'SRC_ERP_PLANT_MASTER' THEN 1
        WHEN 'SRC_LOGISTICS_CARRIER_MASTER' THEN 3
        WHEN 'SRC_ERP_PURCHASE_ORDERS' THEN 13
        WHEN 'SRC_ERP_PURCHASE_ORDER_LINES' THEN 13
        WHEN 'SRC_LOGISTICS_SHIPMENTS' THEN 15
        WHEN 'SRC_LOGISTICS_SHIPMENT_LINES' THEN 15
        WHEN 'SRC_LOGISTICS_RECEIPTS' THEN 14
        WHEN 'SRC_QUALITY_INSPECTIONS' THEN 13
        WHEN 'SRC_PLANNING_REQUIREMENTS' THEN 13
        WHEN 'SRC_IDENTITY_PERSONA_MAP' THEN 5
    END THEN 'PASS' ELSE 'FAIL' END AS status
FROM (
    SELECT 'SRC_SUPPLIER_MASTER' AS table_name, COUNT(*) AS row_count FROM SRC_SUPPLIER_MASTER
    UNION ALL SELECT 'SRC_ERP_PART_MASTER', COUNT(*) FROM SRC_ERP_PART_MASTER
    UNION ALL SELECT 'SRC_ERP_PLANT_MASTER', COUNT(*) FROM SRC_ERP_PLANT_MASTER
    UNION ALL SELECT 'SRC_LOGISTICS_CARRIER_MASTER', COUNT(*) FROM SRC_LOGISTICS_CARRIER_MASTER
    UNION ALL SELECT 'SRC_ERP_PURCHASE_ORDERS', COUNT(*) FROM SRC_ERP_PURCHASE_ORDERS
    UNION ALL SELECT 'SRC_ERP_PURCHASE_ORDER_LINES', COUNT(*) FROM SRC_ERP_PURCHASE_ORDER_LINES
    UNION ALL SELECT 'SRC_LOGISTICS_SHIPMENTS', COUNT(*) FROM SRC_LOGISTICS_SHIPMENTS
    UNION ALL SELECT 'SRC_LOGISTICS_SHIPMENT_LINES', COUNT(*) FROM SRC_LOGISTICS_SHIPMENT_LINES
    UNION ALL SELECT 'SRC_LOGISTICS_RECEIPTS', COUNT(*) FROM SRC_LOGISTICS_RECEIPTS
    UNION ALL SELECT 'SRC_QUALITY_INSPECTIONS', COUNT(*) FROM SRC_QUALITY_INSPECTIONS
    UNION ALL SELECT 'SRC_PLANNING_REQUIREMENTS', COUNT(*) FROM SRC_PLANNING_REQUIREMENTS
    UNION ALL SELECT 'SRC_IDENTITY_PERSONA_MAP', COUNT(*) FROM SRC_IDENTITY_PERSONA_MAP
)
ORDER BY table_name;

-- Total rows
SELECT 'total_rows' AS check_name, SUM(c) AS actual, 110 AS expected,
    CASE WHEN SUM(c) = 110 THEN 'PASS' ELSE 'FAIL' END AS status
FROM (
    SELECT COUNT(*) AS c FROM SRC_SUPPLIER_MASTER UNION ALL SELECT COUNT(*) FROM SRC_ERP_PART_MASTER
    UNION ALL SELECT COUNT(*) FROM SRC_ERP_PLANT_MASTER UNION ALL SELECT COUNT(*) FROM SRC_LOGISTICS_CARRIER_MASTER
    UNION ALL SELECT COUNT(*) FROM SRC_ERP_PURCHASE_ORDERS UNION ALL SELECT COUNT(*) FROM SRC_ERP_PURCHASE_ORDER_LINES
    UNION ALL SELECT COUNT(*) FROM SRC_LOGISTICS_SHIPMENTS UNION ALL SELECT COUNT(*) FROM SRC_LOGISTICS_SHIPMENT_LINES
    UNION ALL SELECT COUNT(*) FROM SRC_LOGISTICS_RECEIPTS UNION ALL SELECT COUNT(*) FROM SRC_QUALITY_INSPECTIONS
    UNION ALL SELECT COUNT(*) FROM SRC_PLANNING_REQUIREMENTS UNION ALL SELECT COUNT(*) FROM SRC_IDENTITY_PERSONA_MAP
);

-- Metadata completeness
SELECT 'metadata_batch_id' AS check_name,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS status
FROM SRC_ERP_PURCHASE_ORDER_LINES WHERE load_batch_id != 'PART4_SYNTHETIC_V1';

-- PO-5001 values
SELECT 'po5001_ordered' AS check_name, ordered_quantity AS actual, '100' AS expected,
    CASE WHEN ordered_quantity = '100' THEN 'PASS' ELSE 'FAIL' END AS status
FROM SRC_ERP_PURCHASE_ORDER_LINES WHERE po_number = 'PO-5001';

-- Edge cases
SELECT 'po5007_no_inspection' AS check_name, COUNT(*) AS actual, 0 AS expected,
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS status
FROM SRC_QUALITY_INSPECTIONS WHERE receipt_id = 'R-8010';

SELECT 'po5010_zero_qty' AS check_name, ordered_quantity AS actual, '0' AS expected,
    CASE WHEN ordered_quantity = '0' THEN 'PASS' ELSE 'FAIL' END AS status
FROM SRC_ERP_PURCHASE_ORDER_LINES WHERE po_number = 'PO-5010';

SELECT 'po5011_missing_orig_date' AS check_name,
    CASE WHEN original_requested_delivery_date IS NULL AND revised_requested_delivery_date IS NOT NULL
         THEN 'PASS' ELSE 'FAIL' END AS status
FROM SRC_ERP_PURCHASE_ORDER_LINES WHERE po_number = 'PO-5011';

SELECT 'po5012_not_a_number' AS check_name, ordered_quantity AS actual,
    CASE WHEN ordered_quantity = 'NOT_A_NUMBER' THEN 'PASS' ELSE 'FAIL' END AS status
FROM SRC_ERP_PURCHASE_ORDER_LINES WHERE po_number = 'PO-5012';

SELECT 'po5013_box_uom' AS check_name, order_uom AS actual,
    CASE WHEN order_uom = 'BOX' AND ordered_quantity = '10' THEN 'PASS' ELSE 'FAIL' END AS status
FROM SRC_ERP_PURCHASE_ORDER_LINES WHERE po_number = 'PO-5013';

-- Source-local identifiers
SELECT 'erp_supplier_codes' AS check_name,
    CASE WHEN COUNT(DISTINCT erp_supplier_code) = 4 THEN 'PASS' ELSE 'FAIL' END AS status
FROM SRC_ERP_PURCHASE_ORDERS;

SELECT 'logistics_supplier_codes' AS check_name,
    CASE WHEN COUNT(DISTINCT logistics_supplier_code) = 4 THEN 'PASS' ELSE 'FAIL' END AS status
FROM SRC_LOGISTICS_SHIPMENTS;

SELECT 'planning_part_codes' AS check_name,
    CASE WHEN planning_part_code = 'PLAN-BAT-01' THEN 'PASS' ELSE 'FAIL' END AS status
FROM SRC_PLANNING_REQUIREMENTS LIMIT 1;
