-- Part 4: RAW data validation
-- Confirms 12 tables loaded with 110 total rows.

USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.RAW;

-- Table row counts
SELECT 'SRC_SUPPLIER_MASTER' AS table_name, COUNT(*) AS row_count FROM SRC_SUPPLIER_MASTER
UNION ALL SELECT 'SRC_ERP_PART_MASTER', COUNT(*) FROM SRC_ERP_PART_MASTER
UNION ALL SELECT 'SRC_ERP_PLANT_MASTER', COUNT(*) FROM SRC_ERP_PLANT_MASTER
UNION ALL SELECT 'SRC_LOGISTICS_CARRIER_MASTER', COUNT(*) FROM SRC_LOGISTICS_CARRIER_MASTER
UNION ALL SELECT 'SRC_ERP_PURCHASE_ORDERS', COUNT(*) FROM SRC_ERP_PURCHASE_ORDERS
UNION ALL SELECT 'SRC_ERP_PURCHASE_ORDER_LINES', COUNT(*) FROM SRC_ERP_PURCHASE_ORDER_LINES
UNION ALL SELECT 'SRC_LOGISTICS_SHIPMENTS', COUNT(*) FROM SRC_LOGISTICS_SHIPMENTS
UNION ALL SELECT 'SRC_LOGISTICS_SHIPMENT_LINES', COUNT(*) FROM SRC_LOGISTICS_SHIPMENT_LINES
UNION ALL SELECT 'SRC_LOGISTICS_RECEIPTS', COUNT(*) FROM SRC_LOGISTICS_RECEIPTS
UNION ALL SELECT 'SRC_QUALITY_INSPECTIONS', COUNT(*) FROM SRC_QUALITY_INSPECTIONS
UNION ALL SELECT 'SRC_PLANNING_REQUIREMENTS', COUNT(*) FROM SRC_PLANNING_REQUIREMENTS
UNION ALL SELECT 'SRC_IDENTITY_PERSONA_MAP', COUNT(*) FROM SRC_IDENTITY_PERSONA_MAP
ORDER BY table_name;

-- Total row count (expect 110)
SELECT 'TOTAL' AS check_name, SUM(row_count) AS total_rows FROM (
    SELECT COUNT(*) AS row_count FROM SRC_SUPPLIER_MASTER
    UNION ALL SELECT COUNT(*) FROM SRC_ERP_PART_MASTER
    UNION ALL SELECT COUNT(*) FROM SRC_ERP_PLANT_MASTER
    UNION ALL SELECT COUNT(*) FROM SRC_LOGISTICS_CARRIER_MASTER
    UNION ALL SELECT COUNT(*) FROM SRC_ERP_PURCHASE_ORDERS
    UNION ALL SELECT COUNT(*) FROM SRC_ERP_PURCHASE_ORDER_LINES
    UNION ALL SELECT COUNT(*) FROM SRC_LOGISTICS_SHIPMENTS
    UNION ALL SELECT COUNT(*) FROM SRC_LOGISTICS_SHIPMENT_LINES
    UNION ALL SELECT COUNT(*) FROM SRC_LOGISTICS_RECEIPTS
    UNION ALL SELECT COUNT(*) FROM SRC_QUALITY_INSPECTIONS
    UNION ALL SELECT COUNT(*) FROM SRC_PLANNING_REQUIREMENTS
    UNION ALL SELECT COUNT(*) FROM SRC_IDENTITY_PERSONA_MAP
);

-- PO-5001 spot check
SELECT 'PO-5001 ordered_quantity' AS check_name, ordered_quantity AS value
FROM SRC_ERP_PURCHASE_ORDER_LINES
WHERE po_number = 'PO-5001' AND po_line_number = '1';

-- SH-9001 shipped quantity
SELECT 'SH-9001 shipped_quantity' AS check_name, shipped_quantity AS value
FROM SRC_LOGISTICS_SHIPMENT_LINES
WHERE shipment_id = 'SH-9001' AND shipment_line_number = '1';

-- SH-9001 accepted quantity
SELECT 'SH-9001 accepted_quantity' AS check_name, accepted_quantity AS value
FROM SRC_QUALITY_INSPECTIONS
WHERE receipt_id = 'REC-001';

-- Planning requirement for Laptop Battery at Pune
SELECT 'Planning P-2001 PLT-01 required' AS check_name, required_quantity AS value
FROM SRC_PLANNING_REQUIREMENTS
WHERE part_id = 'P-2001' AND plant_id = 'PLT-01' AND production_need_date = '2026-08-12';
