-- One-time reset of Part 5 CORE objects only.
USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.CORE;

DROP VIEW IF EXISTS V_PRODUCTION_REQUIREMENT_EVIDENCE;
DROP VIEW IF EXISTS V_SHIPMENT_LINE_ARRIVAL_EVIDENCE;
DROP VIEW IF EXISTS V_PO_LINE_RECEIPT_EVIDENCE;
DROP TABLE IF EXISTS DATA_QUALITY_ISSUE;
DROP TABLE IF EXISTS INSPECTION;
DROP TABLE IF EXISTS RECEIPT;
DROP TABLE IF EXISTS SHIPMENT_LINE;
DROP TABLE IF EXISTS SHIPMENT;
DROP TABLE IF EXISTS PURCHASE_ORDER_LINE;
DROP TABLE IF EXISTS PURCHASE_ORDER;
DROP TABLE IF EXISTS PRODUCTION_REQUIREMENT;
DROP TABLE IF EXISTS CARRIER;
DROP TABLE IF EXISTS PLANT;
DROP TABLE IF EXISTS PART;
DROP TABLE IF EXISTS SUPPLIER;
