-- ChainProof Part 6: controlled reset of Part 6 GOVERNANCE objects only.
USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.GOVERNANCE;

DROP VIEW IF EXISTS V_RECONCILIATION_COMPARISON;
DROP VIEW IF EXISTS V_ENTERPRISE_SUPPLIER_FILL_RESULT;
DROP VIEW IF EXISTS V_LOGISTICS_ON_TIME_ARRIVAL_RESULT;
DROP VIEW IF EXISTS V_PROCUREMENT_ACCEPTED_FILL_RESULT;
DROP VIEW IF EXISTS V_PLANNING_MATERIAL_AVAILABILITY_RESULT;
DROP VIEW IF EXISTS V_QUERY_RESOLUTION_CATALOG;
DROP VIEW IF EXISTS V_METRIC_CATALOG;
DROP VIEW IF EXISTS V_ACTIVE_METRIC_VERSION;

DROP TABLE IF EXISTS RECONCILIATION_SCOPE;
DROP TABLE IF EXISTS USER_PERSONA_MAP;
DROP TABLE IF EXISTS METRIC_ACTIVATION_EVENT;
DROP TABLE IF EXISTS METRIC_APPROVAL;
DROP TABLE IF EXISTS METRIC_CONFLICT_MEMBER;
DROP TABLE IF EXISTS METRIC_CONFLICT;
DROP TABLE IF EXISTS METRIC_ALIAS;
DROP TABLE IF EXISTS METRIC_COMPONENT;
DROP TABLE IF EXISTS METRIC_VERSION;
DROP TABLE IF EXISTS METRIC_DEFINITION;
