-- ChainProof Part 7: controlled reset of Part 7 SEMANTIC objects only.
USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.SEMANTIC;

DROP SEMANTIC VIEW IF EXISTS CHAINPROOF.SEMANTIC.CHAINPROOF_SUPPLY_CHAIN_SV;
DROP VIEW IF EXISTS CHAINPROOF.SEMANTIC.V_METRIC_RECONCILIATION;
DROP VIEW IF EXISTS CHAINPROOF.SEMANTIC.V_PLANNING_MATERIAL_AVAILABILITY;
DROP VIEW IF EXISTS CHAINPROOF.SEMANTIC.V_LOGISTICS_ARRIVAL_PERFORMANCE;
DROP VIEW IF EXISTS CHAINPROOF.SEMANTIC.V_SUPPLIER_FILL_PERFORMANCE;
DROP STAGE IF EXISTS CHAINPROOF.SEMANTIC.PART7_EVALUATION_STAGE;
DROP FILE FORMAT IF EXISTS CHAINPROOF.SEMANTIC.PART7_YAML_FILE_FORMAT;
