-- ChainProof Part 8 controlled reset for the app layer only.
-- Run only when PART8_RESET_APP=1. It does not touch RAW, CORE,
-- GOVERNANCE, or SEMANTIC objects.
USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.APP;

DROP STREAMLIT IF EXISTS CHAINPROOF.APP.CHAINPROOF_APP;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_CONFLICT_SCANNER;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_METRIC_COMPONENT_COMPARISON;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_IMPACT_SIMULATOR_BASE;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_GOVERN_PUBLISH_STATUS;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_GOVERNANCE_TIMELINE;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_CALCULATION_EVIDENCE;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_PERSONA_CONTEXT;
DROP STAGE IF EXISTS CHAINPROOF.APP.PART8_STREAMLIT_STAGE;
