-- ChainProof Part 8 read-only privilege and prerequisite diagnostic.
-- This file never grants privileges.
USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.APP;

SELECT
    CURRENT_USER() AS session_user,
    CURRENT_ROLE() AS active_role,
    CURRENT_WAREHOUSE() AS active_warehouse,
    CURRENT_DATABASE() AS active_database,
    CURRENT_SCHEMA() AS active_schema;

SHOW GRANTS TO ROLE GRIZZLY03_LEARNER_RL;
SET part8_grants_qid = LAST_QUERY_ID();
CREATE OR REPLACE TEMP TABLE PART8_ROLE_GRANTS AS
SELECT * FROM TABLE(RESULT_SCAN($part8_grants_qid));

SELECT
    'CREATE_STREAMLIT_ON_APP_SCHEMA' AS required_capability,
    COUNT_IF("privilege"='CREATE STREAMLIT' AND "granted_on"='SCHEMA' AND "name"='CHAINPROOF.APP') AS matching_grants,
    IFF(COUNT_IF("privilege"='CREATE STREAMLIT' AND "granted_on"='SCHEMA' AND "name"='CHAINPROOF.APP')>0,'PRESENT','CHECK_ROLE_HIERARCHY_OR_ADMIN') AS status
FROM PART8_ROLE_GRANTS
UNION ALL
SELECT
    'CREATE_STAGE_ON_APP_SCHEMA',
    COUNT_IF("privilege"='CREATE STAGE' AND "granted_on"='SCHEMA' AND "name"='CHAINPROOF.APP'),
    IFF(COUNT_IF("privilege"='CREATE STAGE' AND "granted_on"='SCHEMA' AND "name"='CHAINPROOF.APP')>0,'PRESENT','CHECK_ROLE_HIERARCHY_OR_ADMIN')
FROM PART8_ROLE_GRANTS
UNION ALL
SELECT
    'USAGE_ON_QUERY_WAREHOUSE',
    COUNT_IF("privilege"='USAGE' AND "granted_on"='WAREHOUSE' AND "name"='GRIZZLY03_WH'),
    IFF(COUNT_IF("privilege"='USAGE' AND "granted_on"='WAREHOUSE' AND "name"='GRIZZLY03_WH')>0,'PRESENT','CHECK_ROLE_HIERARCHY_OR_ADMIN')
FROM PART8_ROLE_GRANTS;

SELECT
    'PART7_SEMANTIC_VIEW' AS prerequisite,
    COUNT(*) AS matching_objects,
    IFF(COUNT(*)=1,'PASS','FAIL') AS status
FROM CHAINPROOF.INFORMATION_SCHEMA.SEMANTIC_VIEWS
WHERE schema='SEMANTIC'
  AND name='CHAINPROOF_SUPPLY_CHAIN_SV';
