-- Controlled reset for Part 9 deterministic APP evidence objects.
-- Optional Cortex Search and Agent objects are handled separately by the build script
-- because the learner role might not have privileges to manage them.
USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.APP;

DROP VIEW IF EXISTS CHAINPROOF.APP.V_PART9_CAPABILITY_STATUS;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_PUBLICATION_GATE;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_DATA_STEWARD_REVIEW_PACKET;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_PO_EVIDENCE_BINDING;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_TRUSTED_EVIDENCE_SEARCH_SOURCE;
DROP VIEW IF EXISTS CHAINPROOF.APP.V_EVIDENCE_CATALOG;

DROP TABLE IF EXISTS CHAINPROOF.APP.PART9_EVIDENCE_SCOPE_MAP;
DROP TABLE IF EXISTS CHAINPROOF.APP.PART9_EVIDENCE_CHUNK;
DROP TABLE IF EXISTS CHAINPROOF.APP.PART9_EVIDENCE_DOCUMENT;
DROP TABLE IF EXISTS CHAINPROOF.APP.PART9_CAPABILITY_STATUS;
