-- Optional native Cortex Search service for Part 9.
-- The build script treats this as capability-adaptive: failure records a
-- restricted-account fallback rather than failing the deterministic evidence layer.
USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA CHAINPROOF.APP;

CREATE OR REPLACE CORTEX SEARCH SERVICE CHAINPROOF.APP.CHAINPROOF_EVIDENCE_SEARCH
    ON SEARCH_TEXT
    ATTRIBUTES DOCUMENT_ID, DOCUMENT_TYPE, EVIDENCE_TOPIC, SUPPLIER_ID,
               CARRIER_ID, PLANT_ID, METRIC_DEFINITION_ID, SOURCE_PATH
    WAREHOUSE = GRIZZLY03_WH
    TARGET_LAG = '1 day'
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    COMMENT = 'Trusted supplier, carrier, quality, and governance evidence for ChainProof Part 9'
AS
SELECT
    SEARCH_TEXT,
    CHUNK_ID,
    DOCUMENT_ID,
    DOCUMENT_TITLE,
    DOCUMENT_TYPE,
    EVIDENCE_TOPIC,
    SUPPLIER_ID,
    CARRIER_ID,
    PLANT_ID,
    METRIC_DEFINITION_ID,
    SOURCE_PATH,
    SECTION_TITLE,
    CHUNK_TEXT,
    CITATION_LABEL,
    SUPPORTS_METRIC_COMPONENT
FROM CHAINPROOF.APP.V_TRUSTED_EVIDENCE_SEARCH_SOURCE;
