-- ChainProof Part 10 controlled reset.
-- Drops only Part 10 objects in CHAINPROOF.AUDIT.

USE ROLE GRIZZLY03_LEARNER_RL;
USE WAREHOUSE GRIZZLY03_WH;
USE DATABASE CHAINPROOF;
USE SCHEMA AUDIT;

DROP VIEW IF EXISTS CHAINPROOF.AUDIT.V_PART10_RELEASE_HEALTH;
DROP VIEW IF EXISTS CHAINPROOF.AUDIT.V_PART10_CONTROL_SUMMARY;
DROP VIEW IF EXISTS CHAINPROOF.AUDIT.V_PART10_LIMITATION_REGISTER;

DROP TABLE IF EXISTS CHAINPROOF.AUDIT.PART10_CONTROL_RESULT;
DROP TABLE IF EXISTS CHAINPROOF.AUDIT.PART10_KNOWN_LIMITATION;
DROP TABLE IF EXISTS CHAINPROOF.AUDIT.PART10_RELEASE_SNAPSHOT;
